spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://sbfullstackdb.ct98xkmg1eyn.eu-west-2.rds.amazonaws.com:5432/sbfullstackdb
    username: postgres
    password: password12345
    pool-size: 30